[package]
name = "bike_core"
version = "0.1.0"
authors = ["camilojc <camilo@jcoder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
strum = "0.18.0"
strum_macros = "0.18.0"

mysql = "18.2.0"